- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repos
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/safe-upgrade.yml
    - include: tasks/cron.yml
    - include: tasks/timezone.yml
    - include: tasks/update-serial-systemd.yml
    - include: tasks/install-x.yml
    - include: tasks/add_user.yml

