- name: Add the user 'engineer' with a bash shell, appending the group 'admin' user's groups
  ansible.builtin.user:
    name: engineer
    shell: /bin/bash
    groups: admin
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
