- name: Install tasksel
  apt:
    name: tasksel
    state: present
- name: 'Tasksel install xubuntu-core'
  command: tasksel install xubuntu-core
- name: Install XFCE4
  apt:
    name: tasksel
    state: present
- name: Install lightdm
  apt:
    name: lightdm
    state: present
- name: Install xrdp
  apt:
    name: xrdp
    state: present
