- name: Install tasksel
  apt:
    name: tasksel
    state: present
- name: 'Tasksel install ubuntu-budgie-desktop'
  command: tasksel install ubuntu-budgie-desktop
- name: Install lightdm
  apt:
    name: lightdm
    state: present
- name: Install xrdp
  apt:
    name: xrdp
    state: present
