- name: Install htop
  apt:
    name: htop
    state: present
- name: Install timedatectl
  apt: 
    name: timedatectl
    state: present
- name: Install wireshark
  apt:
    name: wireshark
    state: present
- name: Install firefox
  apt:
    name: firefox
    state: present
